/*
 * ak8975c.c
 *
 *  Created on: 24 oct. 2014
 *      Author: ldo
 *
 * A 3-axis electronic compass IC with high sensitive Hall sensor technology.
 */

#include "ak8975c.h"

void
ak8975c_setup (void)
{
  twi_master_setup (); /* i2c to master mode */
}

/*
 * \fn uint8_t mpu9150_read_device_id (void)
 * \brief read device id
 * \return device id
 * */
uint8_t
ak8975c_read_device_id (void)
{
  volatile uint8_t device_id;
  volatile uint8_t reg = WIA;

  twi_read_bytes (AK8975C_ADDRESS, &reg, 1, &device_id);

  return device_id;
}

/*
 * \fn
 * \brief when self-test is set, magnetic field is generated by the internal magnetic source and sensor is measured.
 * \return x, y and z-axis magnetic field value in µT
 * */

xyz
ak8975c_self_test (void)
{
  volatile uint8_t buffer[6];
  volatile uint8_t reg;
  xyz compass;

  /* set power-down mode */
  buffer[0] = CNTL;
  buffer[1] = COMPASS_POWER_DOWN;
  twi_write_bytes (AK8975C_ADDRESS, 2, buffer);

  /* generate magnetic field for self-test */
  buffer[0] = ASTC;
  buffer[1] = GENERATE_FIELD;
  twi_write_bytes (AK8975C_ADDRESS, 2, buffer);

  /* set self-test mode */
  buffer[0] = CNTL;
  buffer[1] = COMPASS_SELF_TEST;
  twi_write_bytes (AK8975C_ADDRESS, 2, buffer);

  /* read measurement data */
  reg = COMPASS_XOUT_L;
  twi_read_bytes (AK8975C_ADDRESS, &reg, 6, buffer);

  compass.x = (double) (buffer[0] + (buffer[1] << 8)) * COMPASS_SENSITIVITY;
  compass.y = (double) (buffer[2] + (buffer[3] << 8)) * COMPASS_SENSITIVITY;
  compass.z = (double) (buffer[4] + (buffer[5] << 8)) * COMPASS_SENSITIVITY;

  /* normal mode */
  buffer[0] = ASTC;
  buffer[1] = 0x00;
  twi_write_bytes (AK8975C_ADDRESS, 2, buffer);

  /* set power-down mode */
  buffer[0] = CNTL;
  buffer[1] = COMPASS_POWER_DOWN;
  twi_write_bytes (AK8975C_ADDRESS, 2, buffer);

  return compass;
}

/*
 * \fn xyz ak8975c_read_xyz (void)
 * \brief when single measurement mode is set,
 * sensor is measured, and after sensor measurement and signal processing is finished,
 * measurement data is stored to measurement data registers, then AK8975C transits to power-down mode automatically
 * \return x, y and z-axis magnetic field value in µT
 * */
xyz
ak8975c_read_xyz (void)
{
  volatile uint8_t buffer[6];
  volatile uint8_t reg;
  xyz compass;

  /* set power-down mode */
  buffer[0] = CNTL;
  buffer[1] = COMPASS_POWER_DOWN;
  twi_write_bytes (AK8975C_ADDRESS, 2, buffer);

  /* single measurement is enable */
  buffer[0] = CNTL;
  buffer[1] = COMPASS_SINGLE_MEASUREMENT;
  twi_write_bytes (AK8975C_ADDRESS, 2, buffer);

  /* read measurement data */
  reg = COMPASS_XOUT_L;
  twi_read_bytes (AK8975C_ADDRESS, &reg, 6, buffer);

  compass.x = (double) (buffer[0] + (buffer[1] << 8)) * COMPASS_SENSITIVITY;
  compass.y = (double) (buffer[2] + (buffer[3] << 8)) * COMPASS_SENSITIVITY;
  compass.z = (double) (buffer[4] + (buffer[5] << 8)) * COMPASS_SENSITIVITY;

  return compass;
}
